version: "3"
services:
  sonarqube:
    image: ghcr.io/pavansingaraju-al/al-sonarqube:1.2
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ~/docker/sonarqube/sq/data:/opt/sonarqube/data
      - ~/docker/sonarqube/sq/logs:/opt/sonarqube/logs
    ports:
      - "9090:9000"
  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/sonarqube/pgsql/:/var/lib/postgresql
      - ~/docker/sonarqube/pgsql/data:/var/lib/postgresql/data
